apiVersion: v1
kind: Pod
metadata:
  name: spring-app
spec:
  containers:
    - name: spring-app
      image: phanngoccanh/spring-cicd:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"